'use strict'

const express = require('express')
const router = express.Router()
const sessionsController = require('./sessions.controller')
const auth = require('../../../auth/auth.service')
const messagingReferrals = require('./messagingReferrals.controller')
const landingPage = require('./landingPage.controller')
const botsController = require('./bots.controller')
const menuController = require('./menu.controller')
const welcomeMessage = require('./welcomeMessage.controller')
const quickReply = require('./quickReply.controller')
const chatbotOptin = require('./chatbotOptin.controller')
const postback = require('./postback.controller')
const seenController = require('./seen.controller')
const deliveryController = require('./delivery.controller')
const unsubscribeController = require('./unsubscribe.controller')

router.post('/sessions', auth.isItWebhookServer(), sessionsController.index)
router.post('/messagingReferrals', auth.isItWebhookServer(), messagingReferrals.index)
router.post('/landingPage', auth.isItWebhookServer(), landingPage.index)
router.post('/talkToHuman', auth.isItWebhookServer(), botsController.index)
router.post('/menuReply', auth.isItWebhookServer(), menuController.index)
router.post('/welcomeMessage', auth.isItWebhookServer(), welcomeMessage.index)
router.post('/quickReply', auth.isItWebhookServer(), quickReply.index)
router.post('/chatbotOptin', auth.isItWebhookServer(), chatbotOptin.index)
router.post('/postback', auth.isItWebhookServer(), postback.index)
router.post('/seen', auth.isItWebhookServer(), seenController.index)
router.post('/delivery', auth.isItWebhookServer(), deliveryController.index)
router.post('/unsubscribe', auth.isItWebhookServer(), unsubscribeController.index)

module.exports = router
