exports.ActionTypes = {
  SEND_CHAT_MESSAGE: 'SEND_CHAT_MESSAGE',
  GET_TEMPLATES: 'GET_TEMPLATES',
  SEND_INVITATION_TEMPLATE: 'SEND_INVITATION_TEMPLATE',
  SET_WEBHOOK: 'SET_WEBHOOK',
  VERIFY_CREDENTIALS: 'VERIFY_CREDENTIALS',
  RESPOND_USING_CHATBOT: 'RESPOND_USING_CHATBOT',
  SEND_TEXT_MESSAGE: 'SEND_TEXT_MESSAGE'
}
