// Constants for different action types

export const TEST = 'TEST'

// Constants for groups
export const FETCH_GROUPS_LIST = 'FETCH_GROUPS_LIST'
export const GROUP_INVITE_LINK = 'GROUP_INVITE_LINK'
export const FETCH_GROUPS_INFO = 'FETCH_GROUPS_INFO'
export const FETCH_CREATED_GROUP = 'FETCH_CREATED_GROUP'
export const FETCH_PARTICIPANTS_LIST = 'FETCH_PARTICIPANTS_LIST'
export const UPDATE_GROUP_ADMIN = 'UPDATE_GROUP_ADMIN'
export const DEMOTE_GROUP_ADMIN = 'DEMOTE_GROUP_ADMIN'
export const DELETE_GROUP_PARTICIPANTS = 'DELETE_GROUP_PARTICIPANTS'
export const ADD_GROUP_PARTICIPANTS = 'ADD_GROUP_PARTICIPANTS'

// Constants for contacts
export const FETCH_CONTACTS_LIST = 'FETCH_CONTACTS_LIST'

// Constants for login
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

// constants for sign up
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

// Constants for user
export const FETCH_USER_DETAILS = 'FETCH_USER_DETAILS'

export const NEW_TEXT_MESSAGE = 'NEW_TEXT_MESSAGE'
export const NEW_LOCATION_MESSAGE = 'NEW_LOCATION_MESSAGE'
export const NEW_IMAGE_MESSAGE = 'NEW_IMAGE_MESSAGE'
export const NEW_VIDEO_MESSAGE = 'NEW_VIDEO_MESSAGE'
export const NEW_AUDIO_MESSAGE = 'NEW_AUDIO_MESSAGE'
export const NEW_VOICE_MESSAGE = 'NEW_VOICE_MESSAGE'
export const NEW_DOCUMENT_MESSAGE = 'NEW_DOCUMENT_MESSAGE'
export const FETCH_SESSIONS = 'FETCH_SESSIONS'

export const UPDATE_MESSAGE_STATUS = 'UPDATE_MESSAGE_STATUS'
