// NOTE: This is temporary file for reference of payload data from airlines
const airlines = [
  {
    'airline_name': 'American Airlines',
    'iata_code': 'AA',
    'icao_code': 'AAL',
    'callsign': 'AMERICAN',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '963',
    'fleet_average_age': '10.9',
    'date_founded': '1934',
    'hub_code': 'DFW',
    'country_name': 'United States',
    'country_iso2': 'US'
  },
  {
    'airline_name': 'Delta Air Lines',
    'iata_code': 'DL',
    'icao_code': 'DAL',
    'callsign': 'DELTA',
    'type': 'scheduled,division',
    'status': 'active',
    'fleet_size': '823',
    'fleet_average_age': '17',
    'date_founded': '1928',
    'hub_code': 'ATL',
    'country_name': 'United States',
    'country_iso2': 'US'
  },
  {
    'airline_name': 'United Airlines',
    'iata_code': 'UA',
    'icao_code': 'UAL',
    'callsign': 'UNITED',
    'type': 'scheduled,division',
    'status': 'active',
    'fleet_size': '715',
    'fleet_average_age': '13.8',
    'date_founded': '1931',
    'hub_code': 'ORD',
    'country_name': 'United States',
    'country_iso2': 'US'
  },
  {
    'airline_name': 'Southwest Airlines Co.',
    'iata_code': 'WN',
    'icao_code': 'SWA',
    'callsign': 'SOUTHWEST',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '712',
    'fleet_average_age': '12.3',
    'date_founded': '1967',
    'hub_code': 'DAL',
    'country_name': 'United States Minor Outlying Islands',
    'country_iso2': 'UM'
  },
  {
    'airline_name': 'China Southern Airlines',
    'iata_code': 'CZ',
    'icao_code': 'CSN',
    'callsign': 'CHINA SOUTHERN',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '498',
    'fleet_average_age': '6.9',
    'date_founded': '2004',
    'hub_code': 'CAN',
    'country_name': 'China',
    'country_iso2': 'CN'
  },
  {
    'airline_name': 'China Eastern',
    'iata_code': 'MU',
    'icao_code': 'CES',
    'callsign': 'CHINA EASTERN',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '407',
    'fleet_average_age': '8.4',
    'date_founded': '1988',
    'hub_code': 'PVG',
    'country_name': 'China',
    'country_iso2': 'CN'
  },
  {
    'airline_name': 'SkyWest Airlines',
    'iata_code': 'OO',
    'icao_code': 'SKW',
    'callsign': 'SKYWEST',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '382',
    'fleet_average_age': '11.1',
    'date_founded': '1972',
    'hub_code': 'SLC',
    'country_name': 'United States Minor Outlying Islands',
    'country_iso2': 'UM'
  },
  {
    'airline_name': 'Air China Limited',
    'iata_code': 'CA',
    'icao_code': 'CCA',
    'callsign': 'AIR CHINA',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '369',
    'fleet_average_age': '6.2',
    'date_founded': '1988',
    'hub_code': 'PEK',
    'country_name': 'China',
    'country_iso2': 'CN'
  },
  {
    'airline_name': 'Federal Express',
    'iata_code': 'FX',
    'icao_code': 'FDX',
    'callsign': 'FEDEX',
    'type': 'scheduled,cargo',
    'status': 'active',
    'fleet_size': '367',
    'fleet_average_age': '21.9',
    'date_founded': '1971',
    'hub_code': 'MEM',
    'country_name': 'United States',
    'country_iso2': 'US'
  },
  {
    'airline_name': 'Ryanair Ltd.',
    'iata_code': 'FR',
    'icao_code': 'RYR',
    'callsign': 'RYANAIR',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '353',
    'fleet_average_age': '6.4',
    'date_founded': '1985',
    'hub_code': 'STN',
    'country_name': 'Ireland',
    'country_iso2': 'IE'
  },
  {
    'airline_name': 'Expressjet',
    'iata_code': 'XE',
    'icao_code': 'BTA',
    'callsign': 'JET LINK',
    'type': null,
    'status': 'active',
    'fleet_size': '319',
    'fleet_average_age': '13.2',
    'date_founded': null,
    'hub_code': null,
    'country_name': 'United States Minor Outlying Islands',
    'country_iso2': 'UM'
  },
  {
    'airline_name': 'THY - Turkish Airlines',
    'iata_code': 'TK',
    'icao_code': 'THY',
    'callsign': 'TURKISH',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '285',
    'fleet_average_age': '6.3',
    'date_founded': '1933',
    'hub_code': 'IST',
    'country_name': 'Turkey',
    'country_iso2': 'TR'
  },
  {
    'airline_name': 'Lufthansa Cargo',
    'iata_code': 'LH',
    'icao_code': 'GEC',
    'callsign': 'LUFTHANSA',
    'type': 'scheduled,cargo',
    'status': 'active',
    'fleet_size': '276',
    'fleet_average_age': '10.9',
    'date_founded': '1994',
    'hub_code': 'FRA',
    'country_name': 'Germany',
    'country_iso2': 'DE'
  },
  {
    'airline_name': 'British Airways',
    'iata_code': 'BA',
    'icao_code': 'BAW',
    'callsign': 'SPEEDBIRD',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '265',
    'fleet_average_age': '12.7',
    'date_founded': '1974',
    'hub_code': 'LHR',
    'country_name': 'United Kingdom',
    'country_iso2': 'GB'
  },
  {
    'airline_name': 'Emirates',
    'iata_code': 'EK',
    'icao_code': 'UAE',
    'callsign': 'EMIRATES',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '249',
    'fleet_average_age': '6.1',
    'date_founded': '1985',
    'hub_code': 'DXB',
    'country_name': 'United Arab Emirates',
    'country_iso2': 'AE'
  },
  {
    'airline_name': 'UPS Airlines',
    'iata_code': '5X',
    'icao_code': 'UPS',
    'callsign': 'UPS',
    'type': 'cargo',
    'status': 'active',
    'fleet_size': '237',
    'fleet_average_age': '17.5',
    'date_founded': '1907',
    'hub_code': 'SDF',
    'country_name': 'United States',
    'country_iso2': 'US'
  },
  {
    'airline_name': 'Easyjet Airline Company Limited',
    'iata_code': 'U2',
    'icao_code': 'EZY',
    'callsign': 'EASY',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '228',
    'fleet_average_age': '6.6',
    'date_founded': '1995',
    'hub_code': 'LGW',
    'country_name': 'United Kingdom',
    'country_iso2': 'GB'
  },
  {
    'airline_name': 'Air France',
    'iata_code': 'AF',
    'icao_code': 'AFR',
    'callsign': 'AIRFRANS',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '226',
    'fleet_average_age': '11.7',
    'date_founded': '1933',
    'hub_code': 'CDG',
    'country_name': 'France',
    'country_iso2': 'FR'
  },
  {
    'airline_name': 'JetBlue',
    'iata_code': 'B6',
    'icao_code': 'JBU',
    'callsign': 'JETBLUE',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '218',
    'fleet_average_age': '8.7',
    'date_founded': '2000',
    'hub_code': 'JFK',
    'country_name': 'United States',
    'country_iso2': 'US'
  },
  {
    'airline_name': 'All Nippon Airways',
    'iata_code': 'NH',
    'icao_code': 'ANA',
    'callsign': 'ALL NIPPON',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '206',
    'fleet_average_age': '9.5',
    'date_founded': '1952',
    'hub_code': 'HND',
    'country_name': 'Japan',
    'country_iso2': 'JP'
  },
  {
    'airline_name': 'Qatar Airways',
    'iata_code': 'QR',
    'icao_code': 'QTR',
    'callsign': 'QATARI',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '176',
    'fleet_average_age': '5.7',
    'date_founded': '1994',
    'hub_code': 'DOH',
    'country_name': 'Qatar',
    'country_iso2': 'QA'
  },
  {
    'airline_name': 'Envoy Air Inc.',
    'iata_code': 'MQ',
    'icao_code': 'ENY',
    'callsign': 'ENVOY',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '171',
    'fleet_average_age': '11.6',
    'date_founded': '2014',
    'hub_code': 'DFW',
    'country_name': 'United States Minor Outlying Islands',
    'country_iso2': 'UM'
  },
  {
    'airline_name': 'Aeroflot',
    'iata_code': 'SU',
    'icao_code': 'AFL',
    'callsign': 'AEROFLOT',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '168',
    'fleet_average_age': '4.3',
    'date_founded': '1923',
    'hub_code': 'SVO',
    'country_name': 'Russia',
    'country_iso2': 'RU'
  },
  {
    'airline_name': 'Shenzhen Airlines',
    'iata_code': 'ZH',
    'icao_code': 'CSZ',
    'callsign': 'SHENZHEN AIR',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '165',
    'fleet_average_age': '5.8',
    'date_founded': '1992',
    'hub_code': 'SZX',
    'country_name': 'China',
    'country_iso2': 'CN'
  },
  {
    'airline_name': 'Air Canada',
    'iata_code': 'AC',
    'icao_code': 'ACA',
    'callsign': 'AIR CANADA',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '164',
    'fleet_average_age': '25',
    'date_founded': '2001',
    'hub_code': 'YYZ',
    'country_name': 'Canada',
    'country_iso2': 'CA'
  },
  {
    'airline_name': 'TAM Linhas Aereas',
    'iata_code': 'JJ',
    'icao_code': 'TAM',
    'callsign': 'TAM',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '163',
    'fleet_average_age': '7.4',
    'date_founded': '1976',
    'hub_code': 'CGH',
    'country_name': 'Brazil',
    'country_iso2': 'BR'
  },
  {
    'airline_name': 'Japan Airlines',
    'iata_code': 'JL',
    'icao_code': 'JAL',
    'callsign': 'JAPANAIR',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '163',
    'fleet_average_age': '9',
    'date_founded': '1951',
    'hub_code': 'HND',
    'country_name': 'Japan',
    'country_iso2': 'JP'
  },
  {
    'airline_name': 'Korean Air',
    'iata_code': 'KE',
    'icao_code': 'KAL',
    'callsign': 'KOREANAIR',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '159',
    'fleet_average_age': '9.5',
    'date_founded': '1962',
    'hub_code': 'ICN',
    'country_name': 'South Korea',
    'country_iso2': 'KR'
  },
  {
    'airline_name': 'Alaska Airlines',
    'iata_code': 'AS',
    'icao_code': 'ASA',
    'callsign': 'ALASKA',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '156',
    'fleet_average_age': '9.5',
    'date_founded': '1932',
    'hub_code': 'SEA',
    'country_name': 'United States',
    'country_iso2': 'US'
  },
  {
    'airline_name': 'Hainan Airlines',
    'iata_code': 'HU',
    'icao_code': 'CHH',
    'callsign': 'HAINAN',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '155',
    'fleet_average_age': '4.9',
    'date_founded': '1989',
    'hub_code': 'HAK',
    'country_name': 'China',
    'country_iso2': 'CN'
  },
  {
    'airline_name': 'SAS',
    'iata_code': 'SK',
    'icao_code': 'SAS',
    'callsign': 'SCANDINAVIAN',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '155',
    'fleet_average_age': '11.1',
    'date_founded': '1946',
    'hub_code': 'CPH',
    'country_name': 'Sweden',
    'country_iso2': 'SE'
  },
  {
    'airline_name': 'Garuda',
    'iata_code': 'GA',
    'icao_code': 'GIA',
    'callsign': 'INDONESIA',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '148',
    'fleet_average_age': '5',
    'date_founded': '1949',
    'hub_code': 'CGK',
    'country_name': 'Indonesia',
    'country_iso2': 'ID'
  },
  {
    'airline_name': 'Cathay Pacific',
    'iata_code': 'CX',
    'icao_code': 'CPA',
    'callsign': 'CATHAY',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '143',
    'fleet_average_age': '8.3',
    'date_founded': '1946',
    'hub_code': 'HKG',
    'country_name': 'Hong Kong',
    'country_iso2': 'HK'
  },
  {
    'airline_name': 'Republic Airlines',
    'iata_code': 'RW',
    'icao_code': 'RPA',
    'callsign': 'BRICKYARD',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '139',
    'fleet_average_age': '5.9',
    'date_founded': '2003',
    'hub_code': 'IND',
    'country_name': 'United States',
    'country_iso2': 'US'
  },
  {
    'airline_name': 'Saudi Arabian Airlines',
    'iata_code': 'SV',
    'icao_code': 'SVA',
    'callsign': 'SAUDIA',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '138',
    'fleet_average_age': '7.8',
    'date_founded': '1945',
    'hub_code': 'JED',
    'country_name': 'Saudi Arabia',
    'country_iso2': 'SA'
  },
  {
    'airline_name': 'Azul Brazilian Airlines',
    'iata_code': 'AD',
    'icao_code': 'AZU',
    'callsign': 'AZUL',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '132',
    'fleet_average_age': '4.3',
    'date_founded': '2008',
    'hub_code': 'VCP',
    'country_name': 'Brazil',
    'country_iso2': 'BR'
  },
  {
    'airline_name': 'Xiamen Airlines',
    'iata_code': 'MF',
    'icao_code': 'CXA',
    'callsign': 'XIAMEN AIR',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '132',
    'fleet_average_age': '5.2',
    'date_founded': '1984',
    'hub_code': 'XMN',
    'country_name': 'China',
    'country_iso2': 'CN'
  },
  {
    'airline_name': 'VRG Linhas Aereas S.A. - Grupo GOL',
    'iata_code': 'G3',
    'icao_code': 'GLO',
    'callsign': 'GOL',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '127',
    'fleet_average_age': '7.8',
    'date_founded': '2000',
    'hub_code': 'CGH',
    'country_name': 'Brazil',
    'country_iso2': 'BR'
  },
  {
    'airline_name': 'Jazz Aviation LP',
    'iata_code': 'QK',
    'icao_code': 'JZA',
    'callsign': 'JAZZ',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '127',
    'fleet_average_age': '16.8',
    'date_founded': null,
    'hub_code': 'YHZ',
    'country_name': 'Canada',
    'country_iso2': 'CA'
  },
  {
    'airline_name': 'Etihad Airways',
    'iata_code': 'EY',
    'icao_code': 'ETD',
    'callsign': 'ETIHAD',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '126',
    'fleet_average_age': '5.8',
    'date_founded': '2003',
    'hub_code': 'AUH',
    'country_name': 'United Arab Emirates',
    'country_iso2': 'AE'
  },
  {
    'airline_name': 'Lan Airlines',
    'iata_code': 'LA',
    'icao_code': 'LAN',
    'callsign': 'LAN',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '126',
    'fleet_average_age': '5.1',
    'date_founded': '2004',
    'hub_code': 'SCL',
    'country_name': 'Chile',
    'country_iso2': 'CL'
  },
  {
    'airline_name': 'Endeavor Air',
    'iata_code': '9E',
    'icao_code': 'FLG',
    'callsign': 'FLAGSHIP',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '122',
    'fleet_average_age': '7.5',
    'date_founded': '2013',
    'hub_code': 'MSP',
    'country_name': 'United States Minor Outlying Islands',
    'country_iso2': 'UM'
  },
  {
    'airline_name': 'Mesa Airlines, Inc.',
    'iata_code': 'YV',
    'icao_code': 'ASH',
    'callsign': 'AIR SHUTTLE',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '122',
    'fleet_average_age': '7.4',
    'date_founded': '1980',
    'hub_code': 'PHX',
    'country_name': 'United States Minor Outlying Islands',
    'country_iso2': 'UM'
  },
  {
    'airline_name': 'Qantas',
    'iata_code': 'QF',
    'icao_code': 'QFA',
    'callsign': 'Q LINK',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '118',
    'fleet_average_age': '9.2',
    'date_founded': '1920',
    'hub_code': 'TMW',
    'country_name': 'Australia',
    'country_iso2': 'AU'
  },
  {
    'airline_name': 'Lion Airlines',
    'iata_code': 'JT',
    'icao_code': 'LNI',
    'callsign': 'LION INTER',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '117',
    'fleet_average_age': '5.7',
    'date_founded': '1999',
    'hub_code': 'CGK',
    'country_name': 'Indonesia',
    'country_iso2': 'ID'
  },
  {
    'airline_name': 'WestJet',
    'iata_code': 'WS',
    'icao_code': 'WJA',
    'callsign': 'WESTJET',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '117',
    'fleet_average_age': '8.4',
    'date_founded': '1995',
    'hub_code': 'YYC',
    'country_name': 'Canada',
    'country_iso2': 'CA'
  },
  {
    'airline_name': 'KLM',
    'iata_code': 'KL',
    'icao_code': 'KLM',
    'callsign': 'KLM',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '116',
    'fleet_average_age': '11.1',
    'date_founded': '1919',
    'hub_code': 'AMS',
    'country_name': 'Netherlands',
    'country_iso2': 'NL'
  },
  {
    'airline_name': 'SIA Cargo',
    'iata_code': 'SQ',
    'icao_code': 'SIA',
    'callsign': 'SINGAPORE',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '111',
    'fleet_average_age': '8.1',
    'date_founded': '1972',
    'hub_code': 'SIN',
    'country_name': 'Singapore',
    'country_iso2': 'SG'
  },
  {
    'airline_name': 'PSA Airlines',
    'iata_code': 'OH',
    'icao_code': 'JIA',
    'callsign': 'BLUE STREAK',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '109',
    'fleet_average_age': '7.1',
    'date_founded': '1979',
    'hub_code': 'DAY',
    'country_name': 'United States',
    'country_iso2': 'US'
  },
  {
    'airline_name': 'Air India',
    'iata_code': 'AI',
    'icao_code': 'AIC',
    'callsign': 'AIR INDIA',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '108',
    'fleet_average_age': '9.4',
    'date_founded': '1948',
    'hub_code': 'DEL',
    'country_name': 'India',
    'country_iso2': 'IN'
  },
  {
    'airline_name': 'Sichuan Airlines',
    'iata_code': '3U',
    'icao_code': 'CSC',
    'callsign': 'SICHUAN',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '107',
    'fleet_average_age': '4.8',
    'date_founded': '1986',
    'hub_code': 'CTU',
    'country_name': 'China',
    'country_iso2': 'CN'
  },
  {
    'airline_name': 'Interglobe Aviation Ltd. dba Indigo',
    'iata_code': '6E',
    'icao_code': 'IGO',
    'callsign': 'IFLY',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '107',
    'fleet_average_age': '4.7',
    'date_founded': '2006',
    'hub_code': 'DEL',
    'country_name': 'India',
    'country_iso2': 'IN'
  },
  {
    'airline_name': 'Vueling',
    'iata_code': 'VY',
    'icao_code': 'VLG',
    'callsign': 'VUELING',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '105',
    'fleet_average_age': '6.7',
    'date_founded': '2004',
    'hub_code': 'BCN',
    'country_name': 'Spain',
    'country_iso2': 'ES'
  },
  {
    'airline_name': 'Alitalia',
    'iata_code': 'AZ',
    'icao_code': 'AZA',
    'callsign': 'ALITALIA',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '102',
    'fleet_average_age': '10.5',
    'date_founded': '1957',
    'hub_code': 'FCO',
    'country_name': 'Italy',
    'country_iso2': 'IT'
  },
  {
    'airline_name': 'AVIANCA',
    'iata_code': 'AV',
    'icao_code': 'AVA',
    'callsign': 'AVIANCA',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '99',
    'fleet_average_age': '4.5',
    'date_founded': '1933',
    'hub_code': 'BOG',
    'country_name': 'Colombia',
    'country_iso2': 'CO'
  },
  {
    'airline_name': 'Virgin Australia',
    'iata_code': 'VA',
    'icao_code': 'VAU',
    'callsign': 'VIRGIN',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '98',
    'fleet_average_age': '6.3',
    'date_founded': '2011',
    'hub_code': 'BNE',
    'country_name': 'Australia',
    'country_iso2': 'AU'
  },
  {
    'airline_name': 'Shuttle America',
    'iata_code': 'S5',
    'icao_code': 'TCF',
    'callsign': 'MERCURY',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '95',
    'fleet_average_age': '11.5',
    'date_founded': null,
    'hub_code': 'FWA',
    'country_name': 'United States Minor Outlying Islands',
    'country_iso2': 'UM'
  },
  {
    'airline_name': 'Shandong Airlines',
    'iata_code': 'SC',
    'icao_code': 'CDG',
    'callsign': 'SHANDONG',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '93',
    'fleet_average_age': '4.6',
    'date_founded': '1994',
    'hub_code': 'TNA',
    'country_name': 'China',
    'country_iso2': 'CN'
  },
  {
    'airline_name': 'Jet Airways',
    'iata_code': '9W',
    'icao_code': 'JAI',
    'callsign': 'JET AIRWAYS',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '92',
    'fleet_average_age': '6.7',
    'date_founded': '1992',
    'hub_code': 'BOM',
    'country_name': 'India',
    'country_iso2': 'IN'
  },
  {
    'airline_name': 'Tianjin Airlines',
    'iata_code': 'GS',
    'icao_code': 'GCR',
    'callsign': 'CHINA DRAGON',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '91',
    'fleet_average_age': '5.2',
    'date_founded': '2009',
    'hub_code': 'TSN',
    'country_name': 'China',
    'country_iso2': 'CN'
  },
  {
    'airline_name': 'Vietnam Airlines',
    'iata_code': 'VN',
    'icao_code': 'HVN',
    'callsign': 'VIETNAM AIRLINES',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '89',
    'fleet_average_age': '5.4',
    'date_founded': '1951',
    'hub_code': 'SGN',
    'country_name': 'Vietnam',
    'country_iso2': 'VN'
  },
  {
    'airline_name': 'COPA Airlines',
    'iata_code': 'CM',
    'icao_code': 'CMP',
    'callsign': 'COPA',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '88',
    'fleet_average_age': '6.1',
    'date_founded': '1947',
    'hub_code': 'PTY',
    'country_name': 'Panama',
    'country_iso2': 'PA'
  },
  {
    'airline_name': 'Shanghai Airlines',
    'iata_code': 'FM',
    'icao_code': 'CSH',
    'callsign': 'SHANGHAI AIR',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '86',
    'fleet_average_age': '5.7',
    'date_founded': '1985',
    'hub_code': 'SHA',
    'country_name': 'China',
    'country_iso2': 'CN'
  },
  {
    'airline_name': 'Air Berlin',
    'iata_code': 'AB',
    'icao_code': 'BER',
    'callsign': 'AIR BERLIN',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '85',
    'fleet_average_age': '8.1',
    'date_founded': '1978',
    'hub_code': 'TXL',
    'country_name': 'Germany',
    'country_iso2': 'DE'
  },
  {
    'airline_name': 'Austrian',
    'iata_code': 'OS',
    'icao_code': 'AUA',
    'callsign': 'AUSTRIAN',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '85',
    'fleet_average_age': '15.8',
    'date_founded': '1957',
    'hub_code': 'VIE',
    'country_name': 'Austria',
    'country_iso2': 'AT'
  },
  {
    'airline_name': 'Spirit Airlines',
    'iata_code': 'NK',
    'icao_code': 'NKS',
    'callsign': 'SPIRIT WINGS',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '84',
    'fleet_average_age': '5.2',
    'date_founded': '1980',
    'hub_code': 'FLL',
    'country_name': 'United States Minor Outlying Islands',
    'country_iso2': 'UM'
  },
  {
    'airline_name': 'Asiana',
    'iata_code': 'OZ',
    'icao_code': 'AAR',
    'callsign': 'ASIANA',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '84',
    'fleet_average_age': '10.3',
    'date_founded': '1988',
    'hub_code': 'ICN',
    'country_name': 'South Korea',
    'country_iso2': 'KR'
  },
  {
    'airline_name': 'China Airlines',
    'iata_code': 'CI',
    'icao_code': 'CAL',
    'callsign': 'DYNASTY',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '83',
    'fleet_average_age': '9.6',
    'date_founded': '1959',
    'hub_code': 'TPE',
    'country_name': 'Chinese Taipei',
    'country_iso2': 'TW'
  },
  {
    'airline_name': 'Allegiant Air LLC',
    'iata_code': 'G4',
    'icao_code': 'AAY',
    'callsign': 'ALLEGIANT',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '83',
    'fleet_average_age': '21.6',
    'date_founded': '1997',
    'hub_code': 'LAS',
    'country_name': 'United States Minor Outlying Islands',
    'country_iso2': 'UM'
  },
  {
    'airline_name': 'Malaysia Airlines',
    'iata_code': 'MH',
    'icao_code': 'MAS',
    'callsign': 'MALAYSIAN',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '83',
    'fleet_average_age': '4.3',
    'date_founded': '1971',
    'hub_code': 'KUL',
    'country_name': 'Malaysia',
    'country_iso2': 'MY'
  },
  {
    'airline_name': 'AirAsia Berhad dba AirAsia',
    'iata_code': 'AK',
    'icao_code': 'AXM',
    'callsign': 'ASIAN EXPRESS',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '82',
    'fleet_average_age': '5.6',
    'date_founded': '1993',
    'hub_code': 'KUL',
    'country_name': 'Malaysia',
    'country_iso2': 'MY'
  },
  {
    'airline_name': 'Thai Airways International',
    'iata_code': 'TG',
    'icao_code': 'THA',
    'callsign': 'THAI',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '81',
    'fleet_average_age': '9.5',
    'date_founded': '1959',
    'hub_code': 'BKK',
    'country_name': 'Thailand',
    'country_iso2': 'TH'
  },
  {
    'airline_name': 'IBERIA',
    'iata_code': 'IB',
    'icao_code': 'IBE',
    'callsign': 'IBERIA',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '78',
    'fleet_average_age': '9.9',
    'date_founded': '1927',
    'hub_code': 'MAD',
    'country_name': 'Spain',
    'country_iso2': 'ES'
  },
  {
    'airline_name': 'flybe',
    'iata_code': 'BE',
    'icao_code': 'BEE',
    'callsign': 'JERSEY',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '69',
    'fleet_average_age': '8.2',
    'date_founded': '2002',
    'hub_code': 'EXT',
    'country_name': 'United Kingdom',
    'country_iso2': 'GB'
  },
  {
    'airline_name': 'Ethiopian Airlines',
    'iata_code': 'ET',
    'icao_code': 'ETH',
    'callsign': 'ETHIOPIAN',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '69',
    'fleet_average_age': '5.9',
    'date_founded': '1945',
    'hub_code': 'ADD',
    'country_name': 'Ethiopia',
    'country_iso2': 'ET'
  },
  {
    'airline_name': 'Jetstar Airways Pty Limited',
    'iata_code': 'JQ',
    'icao_code': 'JST',
    'callsign': 'JETSTAR',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '69',
    'fleet_average_age': '6.2',
    'date_founded': '2004',
    'hub_code': 'MEL',
    'country_name': 'Australia',
    'country_iso2': 'AU'
  },
  {
    'airline_name': 'Wizz Air Hungary Ltd.',
    'iata_code': 'W6',
    'icao_code': 'WZZ',
    'callsign': 'WIZZ AIR',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '68',
    'fleet_average_age': '4.2',
    'date_founded': '2004',
    'hub_code': 'BUD',
    'country_name': 'Hungary',
    'country_iso2': 'HU'
  },
  {
    'airline_name': 'Air Wisconsin Airlines Corporation (AWAC)',
    'iata_code': 'ZW',
    'icao_code': 'AWI',
    'callsign': 'AIR WISCONSIN',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '68',
    'fleet_average_age': '13.8',
    'date_founded': '1965',
    'hub_code': 'ATW',
    'country_name': 'United States Minor Outlying Islands',
    'country_iso2': 'UM'
  },
  {
    'airline_name': 'SWISS',
    'iata_code': 'LX',
    'icao_code': 'SWR',
    'callsign': 'SWISS',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '67',
    'fleet_average_age': '12.9',
    'date_founded': '2002',
    'hub_code': 'ZRH',
    'country_name': 'Switzerland',
    'country_iso2': 'CH'
  },
  {
    'airline_name': 'Trans States Airlines, LLC',
    'iata_code': 'AX',
    'icao_code': 'LOF',
    'callsign': 'WATERSKI',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '65',
    'fleet_average_age': '14.4',
    'date_founded': '1982',
    'hub_code': 'STL',
    'country_name': 'United States',
    'country_iso2': 'US'
  },
  {
    'airline_name': 'EVA Air',
    'iata_code': 'BR',
    'icao_code': 'EVA',
    'callsign': 'EVA',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '65',
    'fleet_average_age': '6.8',
    'date_founded': '1989',
    'hub_code': 'TPE',
    'country_name': 'Chinese Taipei',
    'country_iso2': 'TW'
  },
  {
    'airline_name': 'S7 Airlines',
    'iata_code': 'S7',
    'icao_code': 'SBI',
    'callsign': 'SIBERIAN AIRLINES',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '65',
    'fleet_average_age': '9.3',
    'date_founded': '1992',
    'hub_code': 'DME',
    'country_name': 'Russia',
    'country_iso2': 'RU'
  },
  {
    'airline_name': 'Aeromexico',
    'iata_code': 'AM',
    'icao_code': 'AMX',
    'callsign': 'AEROMEXICO',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '64',
    'fleet_average_age': '7.2',
    'date_founded': '1972',
    'hub_code': 'MEX',
    'country_name': 'Mexico',
    'country_iso2': 'MX'
  },
  {
    'airline_name': 'Interjet',
    'iata_code': '4O',
    'icao_code': 'AIJ',
    'callsign': 'INTERJET',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '63',
    'fleet_average_age': '6.4',
    'date_founded': '2005',
    'hub_code': 'TLC',
    'country_name': 'Mexico',
    'country_iso2': 'MX'
  },
  {
    'airline_name': 'Aerolitoral S.A. de C.V.',
    'iata_code': '5D',
    'icao_code': 'SLI',
    'callsign': 'COSTERA',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '63',
    'fleet_average_age': '8.9',
    'date_founded': '2007',
    'hub_code': 'MTY',
    'country_name': 'Mexico',
    'country_iso2': 'MX'
  },
  {
    'airline_name': 'Capital Airlines',
    'iata_code': 'JD',
    'icao_code': 'CBJ',
    'callsign': 'CAPITAL JET',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '63',
    'fleet_average_age': '8.1',
    'date_founded': '1995',
    'hub_code': 'HAK',
    'country_name': 'China',
    'country_iso2': 'CN'
  },
  {
    'airline_name': 'Pegasus Airlines',
    'iata_code': 'PC',
    'icao_code': 'PGT',
    'callsign': 'SUNTURK',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '63',
    'fleet_average_age': '5.2',
    'date_founded': '1990',
    'hub_code': 'SAW',
    'country_name': 'Turkey',
    'country_iso2': 'TR'
  },
  {
    'airline_name': 'UTair',
    'iata_code': 'UT',
    'icao_code': 'UTA',
    'callsign': 'TJUMAVI',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '63',
    'fleet_average_age': '14.2',
    'date_founded': '1991',
    'hub_code': 'SGC',
    'country_name': 'Russia',
    'country_iso2': 'RU'
  },
  {
    'airline_name': 'Thomson Airways Limited',
    'iata_code': 'BY',
    'icao_code': 'TOM',
    'callsign': 'THOMSON',
    'type': 'scheduled,charter',
    'status': 'active',
    'fleet_size': '62',
    'fleet_average_age': '8',
    'date_founded': '1962',
    'hub_code': 'LTN',
    'country_name': 'United Kingdom',
    'country_iso2': 'GB'
  },
  {
    'airline_name': 'Compass Airlines LLC',
    'iata_code': 'CP',
    'icao_code': 'CPZ',
    'callsign': 'COMPASS',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '62',
    'fleet_average_age': '5.8',
    'date_founded': '2007',
    'hub_code': 'MSP',
    'country_name': 'United States Minor Outlying Islands',
    'country_iso2': 'UM'
  },
  {
    'airline_name': 'TAP Portugal',
    'iata_code': 'TP',
    'icao_code': 'TAP',
    'callsign': 'AIR PORTUGAL',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '62',
    'fleet_average_age': '14.9',
    'date_founded': '1945',
    'hub_code': 'LIS',
    'country_name': 'Portugal',
    'country_iso2': 'PT'
  },
  {
    'airline_name': 'Virgin America',
    'iata_code': 'VX',
    'icao_code': 'VRD',
    'callsign': 'REDWOOD',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '62',
    'fleet_average_age': '6.3',
    'date_founded': '2006',
    'hub_code': 'SFO',
    'country_name': 'United States',
    'country_iso2': 'US'
  },
  {
    'airline_name': 'Volaris',
    'iata_code': 'Y4',
    'icao_code': 'VOI',
    'callsign': 'VOLARIS',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '62',
    'fleet_average_age': '4.5',
    'date_founded': '2006',
    'hub_code': 'TLC',
    'country_name': 'Mexico',
    'country_iso2': 'MX'
  },
  {
    'airline_name': 'Germanwings GmbH',
    'iata_code': '4U',
    'icao_code': 'GWI',
    'callsign': 'GERMAN WINGS',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '61',
    'fleet_average_age': '14.6',
    'date_founded': '2002',
    'hub_code': 'CGN',
    'country_name': 'Germany',
    'country_iso2': 'DE'
  },
  {
    'airline_name': 'Jet2.com Limited',
    'iata_code': 'LS',
    'icao_code': 'EXS',
    'callsign': 'CHANNEX',
    'type': 'scheduled,cargo',
    'status': 'active',
    'fleet_size': '61',
    'fleet_average_age': '21.9',
    'date_founded': '2002',
    'hub_code': 'LBA',
    'country_name': 'United Kingdom',
    'country_iso2': 'GB'
  },
  {
    'airline_name': 'Philippine Airlines',
    'iata_code': 'PR',
    'icao_code': 'PAL',
    'callsign': 'PHILIPPINE',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '59',
    'fleet_average_age': '4.7',
    'date_founded': '1941',
    'hub_code': 'MNL',
    'country_name': 'Philippines',
    'country_iso2': 'PH'
  },
  {
    'airline_name': 'Spring Airlines Limited Corporation',
    'iata_code': '9C',
    'icao_code': 'CQH',
    'callsign': 'AIR SPRING',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '58',
    'fleet_average_age': '3.5',
    'date_founded': '2005',
    'hub_code': 'SHA',
    'country_name': 'China',
    'country_iso2': 'CN'
  },
  {
    'airline_name': 'Frontier Airlines, Inc.',
    'iata_code': 'F9',
    'icao_code': 'FFT',
    'callsign': 'FRONTIER FLIGHT',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '58',
    'fleet_average_age': '7.7',
    'date_founded': '1994',
    'hub_code': 'DEN',
    'country_name': 'United States Minor Outlying Islands',
    'country_iso2': 'UM'
  },
  {
    'airline_name': 'Cebu Pacific Air',
    'iata_code': '5J',
    'icao_code': 'CEB',
    'callsign': 'CEBU AIR',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '57',
    'fleet_average_age': '5',
    'date_founded': '1996',
    'hub_code': 'MNL',
    'country_name': 'Philippines',
    'country_iso2': 'PH'
  },
  {
    'airline_name': 'Norwegian Air Shuttle A.S.',
    'iata_code': 'DY',
    'icao_code': 'NAX',
    'callsign': 'NOR SHUTTLE',
    'type': 'scheduled',
    'status': 'active',
    'fleet_size': '57',
    'fleet_average_age': '3.7',
    'date_founded': '1993',
    'hub_code': 'OSL',
    'country_name': 'Norway',
    'country_iso2': 'NO'
  }
]

const json = {
  'pagination': {
    'limit': 100,
    'offset': 0,
    'count': 100,
    'total': 1669022
  },
  'data': [
    {
      'flight_date': '2019-12-12',
      'flight_status': 'active',
      'departure': {
        'airport': 'San Francisco International',
        'timezone': 'America/Los_Angeles',
        'iata': 'SFO',
        'icao': 'KSFO',
        'terminal': '2',
        'gate': 'D11',
        'delay': 13,
        'scheduled': '2019-12-12T04:20:00+00:00',
        'estimated': '2019-12-12T04:20:00+00:00',
        'actual': '2019-12-12T04:20:13+00:00',
        'estimated_runway': '2019-12-12T04:20:13+00:00',
        'actual_runway': '2019-12-12T04:20:13+00:00'
      },
      'arrival': {
        'airport': 'Dallas/Fort Worth International',
        'timezone': 'America/Chicago',
        'iata': 'DFW',
        'icao': 'KDFW',
        'terminal': 'A',
        'gate': 'A22',
        'baggage': 'A17',
        'delay': 0,
        'scheduled': '2019-12-12T04:20:00+00:00',
        'estimated': '2019-12-12T04:20:00+00:00',
        'actual': null,
        'estimated_runway': null,
        'actual_runway': null
      },
      'airline': {
        'name': 'American Airlines',
        'iata': 'AA',
        'icao': 'AAL'
      },
      'flight': {
        'number': '1004',
        'iata': 'AA1004',
        'icao': 'AAL1004',
        'codeshared': null
      },
      'aircraft': {
        'registration': 'N160AN',
        'iata': 'A321',
        'icao': 'A321',
        'icao24': 'A0F1BB'
      },
      'live': {
        'updated': '2019-12-12T10:00:00+00:00',
        'latitude': 36.28560000,
        'longitude': -106.80700000,
        'altitude': 8846.820,
        'direction': 114.340,
        'speed_horizontal': 894.348,
        'speed_vertical': 1.188,
        'is_ground': false
      }
    }
  ]
}
console.log(airlines)
console.log(json)
