exports.ActionTypes = {
  GET_COMPANY: 'GET_COMPANY',
  RESPOND_USING_CHATBOT: 'RESPOND_USING_CHATBOT',
  SEND_TEXT_MESSAGE: 'SEND_TEXT_MESSAGE',
  SEND_MEDIA_MESSAGE: 'SEND_MEDIA_MESSAGE',
  FETCH_AVAILABLE_NUMBERS: 'FETCH_AVAILABLE_NUMBERS',
  CREATE_ORDER: 'CREATE_ORDER',
  VERIFY_CREDENTIALS: 'VERIFY_CREDENTIALS',
  SET_WEBHOOK: 'SET_WEBHOOK',
  PORT_NUMBER: 'PORT_NUMBER'
}
