module.exports = {
  DYNAMIC: 'DYNAMIC',
  STATIC: 'STATIC',
  PRODUCT_CATEGORIES: 'PRODUCT_CATEGORIES',
  FETCH_PRODUCTS: 'FETCH_PRODUCTS',
  DISCOVER_PRODUCTS: 'DISCOVER_PRODUCTS',
  PRODUCT_VARIANTS: 'PRODUCT_VARIANTS',
  ORDER_STATUS: 'ORDER_STATUS',
  SELECT_PRODUCT: 'SELECT_PRODUCT',
  ADD_TO_CART: 'ADD_TO_CART',
  PROCEED_TO_CHECKOUT: 'PROCEED_TO_CHECKOUT',
  SHOW_MY_CART: 'SHOW_MY_CART',
  RETURN_PRODUCT: 'RETURN_PRODUCT'
}
